export const USER_PROFILE_FULL_NAME_MIN_LENGTH = 2;
export const USER_PROFILE_FULL_NAME_MAX_LENGTH = 100;
export const USER_PROFILE_AVATAR_URL_MAX_LENGTH = 500;
export const USER_DEFAULT_PROFILE_NAME = "Learner";

export const USER_PASSWORD_MIN_LENGTH = 8;
